#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun May  5 21:45:05 2019

@author: allen
"""

import json

data = '''
{
    "name": "Chuck",
    "phone": {
        "type": "intl",
        "number": "+1 7323034456"
    },
    "email":{
        "hide": "yes"
    }
}'''
     
info = json.loads(data)
print('Name:', info["name"])
print('Hide:', info["email"]["hide"])